### ISSUE TITLE
Script is waiting for Move-Item to complete

### ISSUE THREAD

**Issue by msheldont4e** [Tools4everBV/HelloID-Conn-Prov-Target-ActiveDirectory#26]
Currently the script is waiting for the "Move-Item" command to finish, this shouldn't be waiting it should execute in the background per our script policies

**Comment by rschouten97** [comment]
Hi @msheldont4e ,

IMO we can/should change this to a background job. This is indeed the better practice here, especially with the 30 seconds timeout in HelloID Prov.

The only (slight) concern I have with backgrond jobs is that we don't get any feedback about the result, so when testing/troubleshooting we might want to use the actual cmd itself and not start a background Job.
Let's say the error is Access Denied, we won't see that unless we perform the cmd itself. Perhaps we can add a toggle for troubleshooting or dryRun?

**Comment by rschouten97** [comment]
This has been solved/added in later releases.
